name: Compile PDF

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build Templates
        uses: xu-cheng/latex-action@v3
        with:
          root_file: |
            LetterTemplate.tex
            ReportTemplate.tex
            SlidesTemplate.tex
      - name: List files after build (debug)
        run: |
          echo "Listing generated files..."
          ls -alh ./*.pdf  # Make sure the PDFs are being generated
      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: |
            ./LetterTemplate.pdf
            ./ReportTemplate.pdf 
            ./SlidesTemplate.pdf
      - name: Commit PDF 
        run: |
          git pull
          git switch pdf
          git config --local user.email "78648649+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add *.pdf 
          git commit -m "Generated PDFs"
          git push origin pdf 
