name: Compile PDF

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Templates
        uses: xu-cheng/latex-action@v2
        with:
          root_file: |
            LetterTemplate.tex
            ReportTemplate.tex
            SlidesTemplate.tex
      - name: Upload Templates
        uses: actions/upload-artifacts@v4
        with:
          name: PDFs
          path: *.pdf
